package main

import (
	"bufio"
	"fmt"
	"os"
	"unicode"
)

type rng struct{ lo, hi rune }

func ranges(pred func(rune) bool, from rune) []rng {
	var out []rng
	var cur *rng
	for r := from; r <= 0x10FFFF; r++ {
		if pred(r) {
			if cur != nil && cur.hi == r-1 {
				cur.hi = r
				continue
			}
			out = append(out, rng{r, r})
			cur = &out[len(out)-1]
		}
	}
	return out
}

func emitRanges(w *bufio.Writer, name string, rs []rng) {
	fmt.Fprintf(w, "pub const %s = [_]Range{\n", name)
	for _, r := range rs {
		fmt.Fprintf(w, "    .{ .lo = 0x%04X, .hi = 0x%04X },\n", r.lo, r.hi)
	}
	fmt.Fprintf(w, "};\n\n")
}

func main() {
	f, err := os.Create(os.Args[1])
	if err != nil {
		panic(err)
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	defer w.Flush()

	fmt.Fprint(w, `// Code generated from Go's unicode tables. DO NOT EDIT.
//
// Generated by tools/gen_unicode/main.go against the Go standard library so
// that normalization, tokenization and quoting behave exactly as they do in
// Go's unicode and strings packages.
//
// Only code points >= 0x80 are tabulated; callers handle ASCII inline.

pub const Range = struct { lo: u21, hi: u21 };

pub const CaseMapping = struct { from: u21, to: u21 };

fn inRanges(ranges: []const Range, r: u21) bool {
    var lo: usize = 0;
    var hi: usize = ranges.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const entry = ranges[mid];
        if (r < entry.lo) {
            hi = mid;
        } else if (r > entry.hi) {
            lo = mid + 1;
        } else {
            return true;
        }
    }
    return false;
}

`)

	// Only >= 0x80; ASCII handled inline by the caller.
	emitRanges(w, "space_ranges", ranges(unicode.IsSpace, 0x80))
	emitRanges(w, "letter_ranges", ranges(unicode.IsLetter, 0x80))
	emitRanges(w, "digit_ranges", ranges(unicode.IsDigit, 0x80))
	emitRanges(w, "print_ranges", ranges(unicode.IsPrint, 0x80))

	fmt.Fprint(w, `/// unicode.IsSpace for code points >= 0x80.
pub fn isSpaceNonASCII(r: u21) bool {
    return inRanges(&space_ranges, r);
}

/// unicode.IsLetter for code points >= 0x80.
pub fn isLetterNonASCII(r: u21) bool {
    return inRanges(&letter_ranges, r);
}

/// unicode.IsDigit for code points >= 0x80.
pub fn isDigitNonASCII(r: u21) bool {
    return inRanges(&digit_ranges, r);
}

/// unicode.IsPrint for code points >= 0x80.
pub fn isPrintNonASCII(r: u21) bool {
    return inRanges(&print_ranges, r);
}

`)

	var lowers []struct{ from, to rune }
	for r := rune(0x80); r <= 0x10FFFF; r++ {
		l := unicode.ToLower(r)
		if l != r {
			lowers = append(lowers, struct{ from, to rune }{r, l})
		}
	}
	fmt.Fprintf(w, "pub const lower_mappings = [_]CaseMapping{\n")
	for _, m := range lowers {
		fmt.Fprintf(w, "    .{ .from = 0x%04X, .to = 0x%04X },\n", m.from, m.to)
	}
	fmt.Fprintf(w, "};\n\n")

	fmt.Fprint(w, `/// unicode.ToLower for code points >= 0x80.
pub fn toLowerNonASCII(r: u21) u21 {
    var lo: usize = 0;
    var hi: usize = lower_mappings.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const entry = lower_mappings[mid];
        if (r < entry.from) {
            hi = mid;
        } else if (r > entry.from) {
            lo = mid + 1;
        } else {
            return entry.to;
        }
    }
    return r;
}
`)
	fmt.Fprintf(os.Stderr, "space=%d letter=%d digit=%d print=%d lower=%d\n",
		len(ranges(unicode.IsSpace, 0x80)), len(ranges(unicode.IsLetter, 0x80)),
		len(ranges(unicode.IsDigit, 0x80)), len(ranges(unicode.IsPrint, 0x80)), len(lowers))
}
