package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"

	"github.com/justasmonkev/i18n-string-check/internal/extract"
	i18nindex "github.com/justasmonkev/i18n-string-check/internal/index"
	"github.com/justasmonkev/i18n-string-check/internal/report"
	"github.com/justasmonkev/i18n-string-check/internal/scan"
)

const (
	exitOK       = 0
	exitFound    = 1
	exitUsageErr = 2

	modeSource = "source"
	modeTest   = "test"
)

type repeatedFlag []string

func (f *repeatedFlag) String() string {
	return strings.Join(*f, ",")
}

func (f *repeatedFlag) Set(value string) error {
	*f = append(*f, value)
	return nil
}

type config struct {
	enJSON         string
	sourceDir      string
	configPath     string
	minLength      int
	exts           []string
	excludes       []string
	json           bool
	mode           string
	similarityFlow bool
	baseline       string
}

type configFile struct {
	MinLength      *int     `json:"minLength"`
	Ext            []string `json:"ext"`
	Exclude        []string `json:"exclude"`
	JSON           *bool    `json:"json"`
	Mode           string   `json:"mode"`
	SimilarityFlow *bool    `json:"similarityFlow"`
	Baseline       string   `json:"baseline"`
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout io.Writer, stderr io.Writer) int {
	cfg, err := parseArgs(args, stderr)
	if err != nil {
		if err == flag.ErrHelp {
			return exitOK
		}
		fmt.Fprintln(stderr, err)
		return exitUsageErr
	}

	idx, err := i18nindex.Load(cfg.enJSON, cfg.minLength)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return exitUsageErr
	}

	files, err := scan.DiscoverFiles(cfg.sourceDir, scan.Options{
		Extensions: cfg.exts,
		Exclude:    cfg.excludes,
	})
	if err != nil {
		fmt.Fprintln(stderr, err)
		return exitUsageErr
	}

	findings, err := scanAndMatch(files, cfg.minLength, idx, cfg.mode, cfg.similarityFlow)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return exitUsageErr
	}
	for i := range findings {
		findings[i].File = displayPath(findings[i].File)
	}
	if cfg.baseline != "" {
		findings, err = applyBaseline(findings, cfg.baseline)
		if err != nil {
			fmt.Fprintln(stderr, err)
			return exitUsageErr
		}
	}
	summary := report.NewSummary(findings)

	if cfg.json {
		err = report.WriteJSON(stdout, summary)
	} else {
		err = report.WriteText(stdout, summary)
	}
	if err != nil {
		fmt.Fprintln(stderr, err)
		return exitUsageErr
	}
	if summary.Found {
		return exitFound
	}
	return exitOK
}

func parseArgs(args []string, output io.Writer) (config, error) {
	cfg := defaultConfig()
	if err := loadConfigDefaults(&cfg, args); err != nil {
		return cfg, err
	}
	excludes := repeatedFlag(cfg.excludes)
	exts := strings.Join(cfg.exts, ",")

	fs := flag.NewFlagSet("i18n-string-check", flag.ContinueOnError)
	fs.SetOutput(output)
	fs.StringVar(&cfg.configPath, "config", cfg.configPath, "path to i18n-string-check JSON config")
	fs.IntVar(&cfg.minLength, "min-length", cfg.minLength, "ignore literals shorter than N chars after trimming")
	fs.StringVar(&exts, "ext", exts, "comma-separated extensions to scan")
	fs.StringVar(&cfg.mode, "mode", cfg.mode, "scan mode: source or test")
	fs.Var(&excludes, "exclude", "glob pattern to exclude; can be passed multiple times")
	fs.BoolVar(&cfg.json, "json", cfg.json, "output machine-readable JSON instead of text")
	fs.BoolVar(&cfg.similarityFlow, "similarity-flow", cfg.similarityFlow, "also flag likely stale hardcoded translations using conservative similarity matching")
	fs.StringVar(&cfg.baseline, "baseline", cfg.baseline, "path to JSON baseline file generated by --json")
	fs.Usage = func() {
		fmt.Fprint(output, usage())
	}
	if err := fs.Parse(reorderArgs(args, fs)); err != nil {
		return cfg, err
	}
	if fs.NArg() != 2 {
		fs.Usage()
		return cfg, fmt.Errorf("expected <path-to-en.json> and <source-dir>")
	}
	if cfg.minLength < 0 {
		return cfg, fmt.Errorf("--min-length must be >= 0")
	}
	if cfg.mode != modeSource && cfg.mode != modeTest {
		return cfg, fmt.Errorf("--mode must be %q or %q", modeSource, modeTest)
	}

	cfg.enJSON = fs.Arg(0)
	cfg.sourceDir = fs.Arg(1)
	cfg.exts = splitCSV(exts)
	cfg.excludes = excludes
	return cfg, nil
}

func defaultConfig() config {
	return config{
		minLength: 8,
		exts:      []string{"ts", "tsx", "mts", "cts", "js", "jsx", "mjs", "cjs"},
		mode:      modeSource,
	}
}

func loadConfigDefaults(cfg *config, args []string) error {
	path, explicit := configPathFromArgs(args)
	if !explicit {
		path = ".i18n-string-check.json"
		if _, err := os.Stat(path); err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return err
		}
	}
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var file configFile
	if err := json.Unmarshal(content, &file); err != nil {
		return fmt.Errorf("malformed config %s: %w", path, err)
	}
	if file.MinLength != nil {
		cfg.minLength = *file.MinLength
	}
	if file.Ext != nil {
		cfg.exts = file.Ext
	}
	if file.Exclude != nil {
		cfg.excludes = file.Exclude
	}
	if file.JSON != nil {
		cfg.json = *file.JSON
	}
	if file.Mode != "" {
		cfg.mode = file.Mode
	}
	if file.SimilarityFlow != nil {
		cfg.similarityFlow = *file.SimilarityFlow
	}
	if file.Baseline != "" {
		cfg.baseline = file.Baseline
	}
	cfg.configPath = path
	return nil
}

func configPathFromArgs(args []string) (string, bool) {
	for i, arg := range args {
		if arg == "--config" || arg == "-config" {
			if i+1 < len(args) {
				return args[i+1], true
			}
			return "", true
		}
		if strings.HasPrefix(arg, "--config=") {
			return strings.TrimPrefix(arg, "--config="), true
		}
		if strings.HasPrefix(arg, "-config=") {
			return strings.TrimPrefix(arg, "-config="), true
		}
	}
	return "", false
}

func usage() string {
	return `i18n-string-check finds hardcoded strings that match current English translations.

Usage:
  i18n-string-check <path-to-en.json> <source-dir> [flags]

Examples:
  i18n-string-check ./locales/en.json ./src
  i18n-string-check ./locales/en.json ./src --similarity-flow
  i18n-string-check ./locales/en.json ./tests --mode=test
  i18n-string-check ./apps/web/locales/en.json ./apps/web --min-length=8
  i18n-string-check ./en.json ./tests --ext=ts,tsx

Flags:
  --mode=source|test
      source: flag hardcoded current translation values in components/source.
      test: allow direct strings, but flag case/spacing mismatches against current en.json values.
      Default: source

  --min-length=N
      Ignore literals shorter than N chars after trimming.
      Default: 8

  --ext=ts,tsx,mts,cts,js,jsx,mjs,cjs
      Comma-separated extensions to scan.
      Default: ts,tsx,mts,cts,js,jsx,mjs,cjs

  --exclude=pattern
      Glob pattern to exclude.
      Can be passed multiple times.

  --config=path
      JSON config file.
      Default: .i18n-string-check.json when present in the current working directory.

  --baseline=path
      JSON baseline file generated from --json output.

  --json
      Output machine-readable JSON instead of text.

  --similarity-flow
      Also flag likely stale hardcoded translations using conservative similarity matching.

Exit codes:
  0  no hardcoded i18n strings found
  1  hardcoded i18n strings found, likely stale hardcoded translations found, or test translation value mismatches found
  2  IO error / parse error / bad args / malformed en.json

Limitation:
  Similarity matching is intentionally conservative and only applies to longer multi-word strings.
`
}

func splitCSV(value string) []string {
	if value == "" {
		return nil
	}
	parts := strings.Split(value, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part != "" {
			out = append(out, part)
		}
	}
	return out
}

func reorderArgs(args []string, fs *flag.FlagSet) []string {
	var flags []string
	var positional []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if strings.HasPrefix(arg, "-") {
			flags = append(flags, arg)
			name, hasInlineValue := flagName(arg)
			registered := fs.Lookup(name)
			if registered != nil && !hasInlineValue && !isBoolFlag(registered) && i+1 < len(args) {
				i++
				flags = append(flags, args[i])
			}
			continue
		}
		positional = append(positional, arg)
	}
	return append(flags, positional...)
}

func flagName(arg string) (string, bool) {
	trimmed := strings.TrimLeft(arg, "-")
	if trimmed == "" {
		return "", false
	}
	name, value, hasValue := strings.Cut(trimmed, "=")
	_ = value
	return name, hasValue
}

func isBoolFlag(flag *flag.Flag) bool {
	boolFlag, ok := flag.Value.(interface{ IsBoolFlag() bool })
	return ok && boolFlag.IsBoolFlag()
}

type fileResult struct {
	findings []report.Finding
	err      error
}

func scanAndMatch(files []string, minLength int, idx *i18nindex.Index, mode string, similarityFlow bool) ([]report.Finding, error) {
	if len(files) == 0 {
		return nil, nil
	}
	workers := runtime.NumCPU()
	if workers > len(files) {
		workers = len(files)
	}

	jobs := make(chan string, len(files))
	results := make(chan fileResult, len(files))
	var wg sync.WaitGroup

	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for file := range jobs {
				results <- scanOne(file, minLength, idx, mode, similarityFlow)
			}
		}()
	}

	for _, file := range files {
		jobs <- file
	}
	close(jobs)
	wg.Wait()
	close(results)

	var findings []report.Finding
	for result := range results {
		if result.err != nil {
			return nil, result.err
		}
		findings = append(findings, result.findings...)
	}
	sort.Slice(findings, func(i, j int) bool {
		if findings[i].File != findings[j].File {
			return findings[i].File < findings[j].File
		}
		if findings[i].Line != findings[j].Line {
			return findings[i].Line < findings[j].Line
		}
		return findings[i].Column < findings[j].Column
	})
	return findings, nil
}

func scanOne(path string, minLength int, idx *i18nindex.Index, mode string, similarityFlow bool) fileResult {
	literals, err := extract.File(path, minLength)
	if err != nil {
		return fileResult{err: err}
	}
	var findings []report.Finding
	for _, literal := range literals {
		// literal.NormalizedLiteral was already computed during extraction;
		// reuse it instead of re-normalizing the literal in each lookup.
		matches := idx.LookupNormalized(literal.NormalizedLiteral)
		findingType := "hardcoded-translation"
		if len(matches) == 0 && mode == modeSource {
			matches = idx.LookupPatternNormalized(literal.NormalizedLiteral)
		}
		if len(matches) == 0 && mode == modeSource && similarityFlow {
			matches = idx.LookupSimilarNormalized(literal.NormalizedLiteral)
			findingType = "changed-translation-value"
		}
		if len(matches) == 0 {
			continue
		}
		if mode == modeTest {
			if i18nindex.HasExactValue(matches, literal.Literal) {
				continue
			}
			findingType = "test-value-mismatch"
		}
		findings = append(findings, report.Finding{
			File:              literal.File,
			Line:              literal.Line,
			Column:            literal.Column,
			Type:              findingType,
			Literal:           literal.Literal,
			NormalizedLiteral: literal.NormalizedLiteral,
			Matches:           matches,
		})
	}
	return fileResult{findings: findings}
}

func applyBaseline(findings []report.Finding, path string) ([]report.Finding, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var baseline report.Summary
	if err := json.Unmarshal(content, &baseline); err != nil {
		return nil, fmt.Errorf("malformed baseline %s: %w", path, err)
	}
	ignored := map[string]bool{}
	for _, finding := range baseline.Findings {
		ignored[findingSignature(finding)] = true
	}
	filtered := findings[:0]
	for _, finding := range findings {
		if ignored[findingSignature(finding)] {
			continue
		}
		filtered = append(filtered, finding)
	}
	return filtered, nil
}

func findingSignature(finding report.Finding) string {
	keys := make([]string, 0, len(finding.Matches))
	for _, match := range finding.Matches {
		keys = append(keys, match.Key)
	}
	sort.Strings(keys)
	return finding.File + "\x00" + finding.Type + "\x00" + finding.Literal + "\x00" + strings.Join(keys, "\x00")
}

func displayPath(path string) string {
	cwd, err := os.Getwd()
	if err != nil {
		return filepath.ToSlash(path)
	}
	rel, err := filepath.Rel(cwd, path)
	if err != nil || strings.HasPrefix(rel, "..") {
		return filepath.ToSlash(path)
	}
	return filepath.ToSlash(rel)
}
